### ISSUE TITLE
SOSP '19 | TASO: Optimizing Deep Learning Computation with Automatic Generation of Graph Substitutions

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#114]
https://cs.stanford.edu/~padon/taso-sosp19.pdf

from: group meeting

优化计算图的工作

**Comment by yzh119** [comment]
人在香港了？

**Comment by vycezhong** [comment]
手工设计计算图优化目前是rule-based方法，需要专家去写一些rule，非常麻烦，来了一个新的op又得写新的，而且对于不同的data layout(我理解为数据存储的方式)也需要不同的rule，最后是也容易出错.

这篇文章搞了一个自动生成rule的方法，大致分为三步：生成替代 -> 形式化验证 -> 联合data layout优化

1. Graph Subtitution Generation

看table1 ，他们使用的op很少. 单独提到了cat和split op，这两个常常用于fusion，而且配对使用. 

![image](https://user-images.githubusercontent.com/25879526/92499896-ffaa7500-f22e-11ea-8c00-a029ffc076cd.png)


策略是dfs. 对每个子图，输入一些随机tensor，把得到的outputs，和一些其他信息做个hash当作这个子图的fingerprint. 
为了防止float不精确，实际中他们使用的是int作为data type.

fringerprint相同的，就说明这两个子图可以互换，作为rule candidate. 

2. formal verifier

这一部分是对搞了很多"性质" ，比如

![image](https://user-images.githubusercontent.com/25879526/92500426-b60e5a00-f22f-11ea-84f7-b302ab7bac83.png)

然后搞了一个SMT解决. 这部分不熟. 

除此之外还有剪枝，因为很多替换其实都是重复的. 比如

![image](https://user-images.githubusercontent.com/25879526/92500862-5a909c00-f230-11ea-9382-e1003cf69592.png)

这一步结果是得到verified substitution rules

3. joint optimizer

这一步是要输入一个graph，用已经验证过的rule来优化. 

这一步的算法也不复杂. 基于cost的bfs. 找到cost最小的optimal graph. 
![image](https://user-images.githubusercontent.com/25879526/92502734-e4416900-f232-11ea-9a32-e66729919008.png)

cost model就是把各个op的执行时间加起来....注意这里考虑到了data layout.  \alpha > 1

效果当然是好了
![image](https://user-images.githubusercontent.com/25879526/92503509-ebb54200-f233-11ea-9a3c-1c7080a2a263.png)

这个分布图有意思
![image](https://user-images.githubusercontent.com/25879526/92503536-f7a10400-f233-11ea-82c1-194be838d23f.png)

____

感觉搜索会不会是system的万金油...

**Comment by vycezhong** [comment]
> 人在香港了？

人在九江，刚下火车。*hub熟人太多，匿了匿了
