### ISSUE TITLE
Manuscript '20 | Estimating GPU Memory Consumption of Deep Learning Models

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#118]
https://www.microsoft.com/en-us/research/uploads/prod/2020/05/dnnmem.pdf

microsoft出手果然不同凡响

**Comment by yzh119** [comment]
读一下pipedream?

**Comment by vycezhong** [comment]
https://docs.google.com/presentation/d/11ZEuxpbjnFNUQdjj2rMtoQW1mdIfRKxA3deZrHAShCY/edit?usp=sharing

**Comment by vycezhong** [comment]
https://2020.esec-fse.org/details/esecfse-2020-industry-papers/5/Estimating-GPU-Memory-Consumption-of-Deep-Learning-Models

看来是中了ESEC, xmsl
