### ISSUE TITLE
NIPS '17 | The Reversible Residual Network: Backpropagation Without Storing Activations

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#119]
https://arxiv.org/pdf/1707.04585.pdf

原来还有这么NB的方法

**Comment by ZheyuYe** [comment]
reformer就是用的这个idea

**Comment by vycezhong** [comment]
稍微看了下

看懂这张图我觉得就OK了

![image](https://user-images.githubusercontent.com/25879526/94370293-bb214380-0121-11eb-86ee-8d148867db0f.png)

输入要拆分为x1 x2，根据channel拆分. 对于每个block，输入(x1, x2)，输出(y1, y2)

严格来讲，应该是下式所示. 左边是FW，右边是reverse. 注意z1和y1在计算图中是两个节点. 
![image](https://user-images.githubusercontent.com/25879526/94370748-47346a80-0124-11eb-8f0a-47ef1922a0f9.png)

最后要理解这个算法，有点费劲
![Screenshot-20200928004938-1798x844](https://user-images.githubusercontent.com/25879526/94370782-85318e80-0124-11eb-88b8-0eaa5f707e82.png)

3-4行是重构x1 x2. 第5行之所以是这样，因为z1是有两个out，一个去了y2，另一个赋值为y1. 赋值为y1的导数直接传回来，就是 grad(y1); 另一个是 y2 = x2 + G(z1)，x2和z1没关系，dy2 / dz1 = d G(z1) / dz1，按照chain rule，最终导数要乘上 grad(y2)，所以得到了第5行的式子. x2也有两个out，一个直接加到了y2，所以直接拿到了grad(y2)，另一个是 z1 = x1 + F(x2)，所以同样可以得到是 (dF / dx2) grad(z1)，两个加起来就是最终导数. 第7行，x1只有一个out，就是参与了 z1 = x1 + F(x2)，所以直接赋值为grad(z1). 剩下两行是参数的导数都很好理解，F只跟z1相关，G只跟y2相关，乘上回传导数. 

所以额外的开销是BP时要重新重构一遍输入，也就是要做一次FW的reverse过程，所以开销就是一遍FW，大概是33%. activation开销是降低到了O(1)， 这要优于 #120  的O(sqrt(N)). 

看上去很promising. 但是其实有点问题. 第一个是为了不损失信息，卷积的stride必须是1，不然不能重构回来. 这个，怎么说，basically ok. 说明Pool层是无法重构的. 这个影响不是很大，基本可以接受. 

但是第二个问题就有点trouble了. 因为float有误差，重构的x1 x2和原来的真实的输入，其实是有些微偏差的，反向传播的时候，这种偏差会慢慢积累，导致前面的层越来越不准确. 糟糕的是这种误差居然还不小，如下图所示. 

![Screenshot-20200928010844-1218x1012](https://user-images.githubusercontent.com/25879526/94371184-2de0ed80-0127-11eb-8656-4bd87297508f.png)

但是作者说这个偏差对accuracy没有影响. 如下图, 

![image](https://user-images.githubusercontent.com/25879526/94371211-77c9d380-0127-11eb-8ef2-44243f158613.png)


___

看完paper找到了久违的激动，很少有paper能如此打动我了. 

比较smart，clean

误差这件事确实没想到，FP32误差在1e-7的量级，一般不是一个问题，没想到这里误差有点non-trivial. 很期待有后续工作去解决.

**Comment by yzh119** [comment]
所以partly reversible，有没有兴趣做。

**Comment by yzh119** [comment]
虽然你不做的话年底也应该有paper发出来了。。

**Comment by vycezhong** [comment]
> 所以partly reversible，有没有兴趣做。

没人带啊qwq
