### ISSUE TITLE
arXiv '16 | Training Deep Nets with Sublinear Memory Cost

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#120]
https://arxiv.org/pdf/1604.06174.pdf

经典

**Comment by yzh119** [comment]
其实源头是这篇https://dl.acm.org/doi/10.1145/347837.347846，二十年前的老古董了

**Comment by yzh119** [comment]
autodiff的技术相当之成熟，可惜他们没赶上DL这波浪潮，具体历史可以参考http://www.autodiff.org/，最早的文献可以追溯到60年代。

PyTorch的自动求导基本上是最原始的算法，比autodiff的SOTA差了几个时代，可是ML的人并不在乎，自由度才是王道。

**Comment by vycezhong** [comment]
这篇文章主要讲了两件事：我们可以用分析计算图，找到其中可以做inplace和memory sharing的优化; 第二是提出了trade computation for memory的方法。

第一件事我觉得 MXNet这个doc讲的挺明白了 https://mxnet.apache.org/versions/1.6/api/architecture/note_memory#in-place-operations 这个是一定有收益的，所以默认一定会做

主要看trade computation for memory. 

![image](https://user-images.githubusercontent.com/25879526/94358174-b339b300-00d1-11eb-8b21-e5d692f47a19.png)

要注意最后的memory cost其实是这样的，因为可以重复利用内存

![image](https://user-images.githubusercontent.com/25879526/94358185-c3519280-00d1-11eb-9fdd-8a63a02d9a42.png)

有时候看dalao讨论的时候会看到mirror这个词，应该指的是recomputation的forward，有点像把FW path给mirror一遍. 

![Screenshot-20200927145832-1402x706](https://user-images.githubusercontent.com/25879526/94358212-f562f480-00d1-11eb-9c6b-8cb2a812a28f.png)

最后是给了两个算法：一个是假设各层内存分布均匀，理论上得到一个O(sqrt(N))的方法. 另一个是给定memory budget，然后greedy搜，如图

![image](https://user-images.githubusercontent.com/25879526/94358254-4d99f680-00d2-11eb-85dd-0a9f17ff1207.png)

实验懒得挂了，反正nb就完了.

____

给我的启发是，recomputation可以这样形式化，用一个0-1向量表示每个op做不做drop. 不同的recomputation的算法其实是在讨论怎么给出这个0-1向量，s.t 各种限制.

**Comment by vycezhong** [comment]
> 其实源头是这篇https://dl.acm.org/doi/10.1145/347837.347846
> 二十年前的老古董了

草，你这也太快了

**Comment by vycezhong** [comment]
> autodiff的技术相当之成熟，可惜他们没赶上DL这波浪潮，具体历史可以参考http://www.autodiff.org/ ，早期的文献可以追溯到60年代。
> 
> PyTorch的自动求导基本上是最原始的算法，比autodiff的SOTA差了几个时代，可是ML的人并不在乎，自由度才是王道。

我还以为是BP那个时候才有的
