### ISSUE TITLE
ICML '19 | Graph U-Nets

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#127]
https://arxiv.org/pdf/1905.05178.pdf

from: group meeting

**Comment by yzh119** [comment]
graph pooling models doesn't work, not worth trying.

**Comment by vycezhong** [comment]
搞了gPool和gUnpool操作，然后基于此搞了类似U-Net的结构

gPool示意图
![image](https://user-images.githubusercontent.com/25879526/95824175-6ad0f500-0d61-11eb-969f-1f115a6cfb36.png)

gUnpool
![image](https://user-images.githubusercontent.com/25879526/95835108-6233eb00-0d70-11eb-8bc6-0313d5a2eb73.png) 
未选中的就是zeros. 

这里有问题. 比如pool后图变成不连通的了.... 所以他们对GCN做了些调整. 比如使用A^2 而不是A, A^2其实是2阶邻接矩阵，另外还用了\hat{A} = A + 2I 而不是原来的 \hat{A} = A + I .... well 

实验当然是好了，不然怎么发表（逃
![image](https://user-images.githubusercontent.com/25879526/95835932-6f9da500-0d71-11eb-8236-2c6a836c608e.png)

这里的inductive和transdutive感觉可以理解为类似于unsupervised learning和supervised learning? i am not sure.

**Comment by vycezhong** [comment]
这个pooling感觉是attention-based pooling

**Comment by yzh119** [comment]
inductive的意思是在一张图上训，在另一张图上测（图结构不同）
transductive的意思是在一张图上训，但是有的节点是没有label的，在同一张图上测（在这些训练的时候未知label的节点上预测）。

做实验的这几个数据集，一个完整的训练流程（几百轮）大概几秒钟，比的就是调参水平，随机种子设的好，结果就好；cuda上atomic操作带来的误差比模型和模型之间的差距可能都大。

**Comment by yzh119** [comment]
GNN的paper是不是实际上能work，可以看[ogb leaderboard](https://ogb.stanford.edu/docs/leader_nodeprop/)，基本上找不到带pooling字样的，而且很早的model(GCN, GAT, GraphSAGE)到现在还很稳健地可以排在前面，可见到目前为止魔改的模型还没找到门道。

**Comment by vycezhong** [comment]
> GNN的paper是不是实际上能work，可以看[ogb leaderboard](https://ogb.stanford.edu/docs/leader_nodeprop/)，基本上找不到带pooling字样的，而且很早的model(GCN, GAT, GraphSAGE)到现在还很稳健地可以排在前面，可见到目前为止魔改的模型还没找到门道。

great!

**Comment by vycezhong** [comment]
明白了，这就从排行榜从头往下看.
