### ISSUE TITLE
NeurIPS '20 | AutoSync: Learning to Synchronize for Data-Parallel Distributed Deep Learning

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#134]
https://papers.nips.cc/paper/2020/file/0a2298a72858d90d5c4b4fee954b6896-Paper.pdf

distributed training里面有很多参数，这篇文章讲如何自动搜索这些参数.

**Comment by vycezhong** [comment]
最近也在考虑这个问题：有些优化策略几乎必定是有收益的，如mixed precision，communication scheduling; 但有些是有trade-off的，如operator partition / grad compression/ tensor fusion/ grad partition ...，需要做搜索去适应不同的集群硬件情况. 

autosync主要目标是想
![image](https://user-images.githubusercontent.com/25879526/100201241-c7b3f380-2f3a-11eb-8bb4-0f17f6a04941.png)
G是计算图，D是指设备，S是优化策略，C是限制. f是per-iteration runtime. 

本文考虑主要考虑通信优化，列了4个策略
1. partition: 大gradient分成小块pipeline传输 
2. placement: 应该是指ps的workload assignment. 
3. sync architecture: 对于ps，考虑是否做了hierarchical aggregation. 对于all-reduce，考虑是否做了merge group和device order. merge group应该就是tensor fusion，device order是指tree or ring. 
4. grad compression

以上几种策略都是以单个gradient为粒度的，也就是说，总的搜索空间，应该是|V| x |S|，即图的节点数目 * 策略空间大小.   

我们最后是想找到一个最佳的策略，使得per-iteration runtime最小. 所以可以看到，搜索空间还是非常大的. 

autosync做了两件事，
1. simulator：给定一个(G, D, S)，搞一个simulator去预测计算时间f. 这里用了ML model来预测. 
2. knowledge-guided search: 首先为了缩小搜索范围，设置了一些constraints (C). 在开始的时候，用这个simulator去从strategy candidates中选择策略（这时候还不一定是最优的），然后按照这个策略到真实cluster上运行，得到真实的执行时间，接着用这些数据去训练simulator的ML model（相当于是adapt to具体的G和D），得到更好的策略. 如此直到优化效果满意为止. 

示意图如下:
![image](https://user-images.githubusercontent.com/25879526/100202552-6c830080-2f3c-11eb-9f1d-4b76fa314fa8.png)

**simulator**

 如果把(G, D）称之为domain，那么首先弄一些domain-agnostic的features. domain-agnostic feature分为两部分：一部分是predefine，一部分是raw features. 比如，predefine的features包括每个operator的 [网络传输时间，网络overhead和GPU memory copy时间]，然后考虑其中最长时间和总计时间，以及PS和allreduce两种架构，得到最终的predefine features. raw features基本是上面几种策略的具体参数以及设备参数，比如选了哪一种gradient compression方法，如何做workload assignment，网络带宽，设备数目等等.

然后作者尝试了三种模型:
1. Linear Model: 只使用predefine features, 这里其实make sense. 这里的rational是[网络传输时间，网络overhead和GPU memory copy时间]加权加起来，基本就是总的通信时间. 
2. RNN: 使用RNN是因为|V|是变长的. 这里使用所有features.  
3. GAT: 也使用所有features. 

loss不是MSE. 因为直接预测其实是很难做到准确的. 这里用了pair-wise logistic ranking loss. 
![image](https://user-images.githubusercontent.com/25879526/100207264-5c6e1f80-2f42-11eb-9a49-b829a21e4f14.png)

上式考虑了partition的overhead - 如果partition数目过多有惩罚. 这是为了防止模型被训练成疯狂做partition.

**knowledge-guided search**

为了缩小搜索空间，做了两个限制:
1. workload balance. 针对第二个优化策略placement，要求尽量分配均匀.
2. adjacent merging: 针对第三个优化策略中的allreduce，要求相邻的gradient才能做fusion. 极端的反例是，模型的头尾两个tensor做fusion...

在选择最终策略的时候，首先会求解一组最终候选策略(final set of candidates)，这里会用相似度作为惩罚项，避免选出来的策略都很相似. 


实验

最后是使用了RNN模型. GAT效果较差可能是数据量太少. Linear太简单效果一般.
![image](https://user-images.githubusercontent.com/25879526/100214892-5a5c8e80-2f4b-11eb-8fe2-02a51d543ef6.png)

![image](https://user-images.githubusercontent.com/25879526/100213158-41eb7480-2f49-11eb-92c6-1e37f3eb5e4c.png)
优化力度还不错. 

但这样有个问题，每次换一个(G, D)，即换个模型或者换个机器，就得重新跑一遍这种trail-error式的搜索优化策略. 这太麻烦了. 所以作者借鉴transfer learning，研究了transfer trained simulator. 大意是搞了一个数据集，这个数据集考虑了几种典型的模型和机器环境，然后发现用pretrained simulator可以减少trails的次数. 

![image](https://user-images.githubusercontent.com/25879526/100213648-d48c1380-2f49-11eb-86d6-08cc3db6d6a4.png)
（图中A/B指不同的机器环境）

____


感觉这是篇system paper投到AI会议... 

注意这篇文章做的是co-optimization，同时考虑几个优化变量. 感觉方法还挺直接的，用个ML model来预测执行时间，根据执行时间来选择策略. 缺点是
1. 简化太多： 比如考虑总的执行时间简化为max(T_comp, T_comm). 也没有考虑压缩开销. 这个可以理解，用ML model也是为了弥补直接预测的困难. 但引入ML model的同时，也带来了需要训练的开销. 
2. 还是需要上机跑，虽然每次trail跑的时间不长（50个iterations），但是看上去大概要跑100-200个的trails，这不是段小时间. 

transfer trained simulator是个亮点. 不过需要去弄数据集就很麻烦. 不过如果是在云上跑那还好，机器规格都统一.

**Comment by yzh119** [comment]
Hao Zhang的文章，基本上只投ML的会

**Comment by vycezhong** [comment]
> Hao Zhang的文章，基本上只投ML的会

可能受老板影响？ BTW, 我觉得他pub太耀眼了.
