### ISSUE TITLE
ICLR '15 | Adam: A Method for Stochastic Optimization

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#135]
https://arxiv.org/pdf/1412.6980.pdf

我主要是来读证明的（逃

**Comment by yzh119** [comment]
Adam还是有点意思的

**Comment by vycezhong** [comment]
> Adam还是有点意思的

没办法，bert非要用adam.

**Comment by vycezhong** [comment]
![adam-1](https://user-images.githubusercontent.com/25879526/101369457-4e75b280-38e3-11eb-9a9c-02d1a4218024.png)
![adam-2](https://user-images.githubusercontent.com/25879526/101369462-503f7600-38e3-11eb-95ca-cf920ca1df3b.png)
