### ISSUE TITLE
SOSP '19 | Lineage Stash: Fault Tolerance Off the Critical Path

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#164]
http://cs-people.bu.edu/liagos/material/sosp19.pdf

8.1更新: 这篇文章我零碎看过很多次了. 是我一下子吃不下的论文. 只能读一点写点笔记了.

**Comment by vycezhong** [comment]
了解这篇paper的basic idea看slide就比较清楚了. 

https://sosp19.rcs.uwaterloo.ca/slides/wang.pdf

确实很有意思. 其实就是用causal logging #172 的方法来异步保存lineage. 

我关注的重点是其中的两个实验——5.2.1 & 5.2.2

![image](https://user-images.githubusercontent.com/25879526/127773210-8520685c-cc17-484f-9495-465e9fa3ae61.png)
![image](https://user-images.githubusercontent.com/25879526/127773215-c7c6d1df-c353-4974-91f3-8518f7dbcfd8.png)

我简直不敢相信. LS能比Horovod恢复快4倍？？Lineage其实只是保存了task信息而已，但DL里面task信息早就知道了，不就是计算图么？这东西要存么？？？存了有啥用？？还不是要回滚到checkpoint然后重新计算？？？保存了lineage有啥difference么？

后来仔细看了5.2.1，发现里面有这么一句话. 

> For the lineage-based systems, the failed process retrieves all lost allreduce outputs since the last checkpoint from the remaining nodes' in-memory stores and replays the last allreduce iteration from the lineage. 

艹. 搞半天原来除了最后一个iteration的结果要重新计算（因为没有），其他结果你都cache在memory了...这还说个几把. 肯定要比checkpoint回滚快一个数量级好吧. 所以Distributed training (5.2.2)那个实验也一样，几百个iteration的gradients都cache在memory了，直接reapply就行了，所以能快这么多. 这两个实验简直是在耍赖...这根本不是因为LS好嘛.

**Comment by vycezhong** [comment]
[Lineage Stash_ Fault Tolerance Off the Critical Path (SOSP '19).pptx](https://github.com/vycezhong/read-papers/files/7613591/Lineage.Stash_.Fault.Tolerance.Off.the.Critical.Path.SOSP.19.pptx)

**Comment by YangZhou1997** [comment]
Hi Yuchen, 

在网上看到你在分析这篇paper，我有一个问题：如果需要tolerate 3个node failure，那在invoke一个task前，LS至少需要把task lineage写到2个remote nodes上（因为local node已经存了一份）；在没有收到这两个node的ack前，LS不能invoke这个task。否则，LS无法保证exact-once

请问我这样理解正确吗？（paper实在写的太迷了

Best,
Yang

**Comment by yuchenzhong** [comment]
> Hi Yuchen,
> 
> 在网上看到你在分析这篇paper，我有一个问题：如果需要tolerate 3个node failure，那在invoke一个task前，LS至少需要把task lineage写到2个remote nodes上（因为local node已经存了一份）；在没有收到这两个node的ack前，LS不能invoke这个task。否则，LS无法保证exact-once
> 
> 请问我这样理解正确吗？（paper实在写的太迷了
> 
> Best, Yang

@YangZhou1997 你好！ 我也不是很清楚，我觉得看上去是这样，但论文又提到跟通信结构有关，比如5.1节实验说ring这样的通信结构，tolerate f个simultaneous failures就必须要forward f次. 不过论文4.3节在讨论这部分的时候引用了[4]，或许有参考意义.
