### ISSUE TITLE
SOSP '19 | PipeDream: Generalized Pipeline Parallelism for DNN Training

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#167]
https://dl.acm.org/doi/pdf/10.1145/3341301.3359646

不鸽了

**Comment by vycezhong** [comment]
非常经典的paper. 粗略读了一下. 

![image](https://user-images.githubusercontent.com/25879526/122670531-21d91680-d1f5-11eb-8b5b-0a55a7e5dcaa.png)


三点贡献:
1. 自动决定DNN placement.抽象成了一个DP问题. 允许某个stage用data-parallelism. 很好. 
2. 1F1B. 其实就是提高了backward的优先级. 
3. weight stash. 这是因为他们在每次backward后都直接做update, 所以等到做BW的时候，参数已经被更新过几次了，已经不是当时做FW时的参数了. 所以他们需要cache之前的weight. 越在pipeline前面，所需要cache的weight版本越多. 

![image](https://user-images.githubusercontent.com/25879526/122670525-1be33580-d1f5-11eb-93ef-bac9fa502681.png)

其实weight stash是没有必要的. 如果BW后不做update. 等到一个统一的时间做update也可以. 参考该作者最近的后续文章 #188

**Comment by vycezhong** [comment]
再读有感: 这种能把如何partition pipeline形式为化为一个DP问题，这就体现了insights. 这比暴力搜索要好的多. 确实，搜索往往是下策. 确实是这样，很多系统paper不过是做了两件事: 1) 形式化为一个优化问题. 2) 求解这个问题. 有的问题贪心就能求解，有的需要动态规划，有的需要搜索（暴力/启发式）...

**Comment by vycezhong** [comment]
注意，Pipedream是由staleness的！

因为batch 1, batch 2, batch 3, batch 4都是根据weight 1算出来的，但是更新的时候却是顺序更新，这和vanilla SGD是不一样的.

**Comment by vycezhong** [comment]
paritition问题确实具有最优子结构: 最优解是各阶段的时间都相等，而各阶段相等自然是子问题的最优解. 

差不多看懂了这个DP. 这里面有两个概念，A表示的是layer i -> layer j之间最慢的stage所需要花的时间. layer i -> layer j之间可能有很多stages. 然后T表示的是假如layer i -> layer j是一个stage，它需要花多少时间. 

所以考虑子问题的时候，考虑layer i -> layer s -> layer j，然后把layer s -> layer j当作是一个stage，而layer i -> layer s可以有很多stages. 另外还需要给新分配出来的stage m'个workers. 那么前面那段还剩m - m'个workers. 于是就有了下式. 需要遍历所有s的位置(i <= s < j)，还需要遍历所有m' ( 1 <= m' < m). 

![image](https://user-images.githubusercontent.com/25879526/122930987-0d388200-d39f-11eb-82ef-3a2c4ba39458.png)

而T怎么求呢

![image](https://user-images.githubusercontent.com/25879526/122934148-d9129080-d3a1-11eb-929c-bbacc25b716a.png)

第二项是data parallelism的通信时间. 第一项其实是计算时间. 

初始化: 
![image](https://user-images.githubusercontent.com/25879526/122934479-23940d00-d3a2-11eb-915f-cb53fa8b4587.png)

还有一个
![image](https://user-images.githubusercontent.com/25879526/122934672-51795180-d3a2-11eb-8cfe-bd8b60f67c76.png)

**Comment by dartao** [comment]
关于Tk的第一项，应该是layer i  ->   layer j 作为一个单独的stage的计算时间，而这里的Ak表示的不是 layer i  ->   layer  j 中最慢stage的计算时间吗？
