### ISSUE TITLE
arXiv '21 | ZeRO-Offload: Democratizing Billion-Scale Model Training

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#193]
https://arxiv.org/pdf/2101.06840.pdf

去年看过后写了一页slide, 结果今天看不懂当时写的slide....只能找paper重看.

USENIX模板啊.

**Comment by vycezhong** [comment]
这不就是PS吗？？？？？？？？？？怎么还起了个花里胡哨的名字？


图还画错了，右上角的4M删掉. 
![Screenshot-20210524182350-728x682](https://user-images.githubusercontent.com/25879526/119334049-393be700-bcbd-11eb-87ae-76d7a6b6317d.png)

**Comment by vycezhong** [comment]
注意这里offload值的是model states.

**Comment by vycezhong** [comment]
这篇居然中了ATC '21....

**Comment by vycezhong** [comment]
那个delayed parameter update和 #206  PipeDream-2BW是一回事，有两份weight，用g_{t-1}来更新x_t.

**Comment by ENg-122** [comment]
请教个问题啊 那个梯度累积的微批次数是应该如何确定啊？
