### ISSUE TITLE
NIPS '15 | Character-level Convolutional Networks for Text Classification

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#48]
https://arxiv.org/pdf/1509.01626.pdf

from: charCNN

**Comment by vycezhong** [comment]
输入是char的one-hot embebdding，shape是[l_0, m]，l_0是一个固定的长度，文中取1014，多余的字符不要. m是字符表的大小，文中是70. 然后就是喂到CNN+FC. 

这也能发？

**Comment by yzh119** [comment]
笑死
