### ISSUE TITLE
arXiv '16 | Layer Normalization

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#71]
https://arxiv.org/pdf/1607.06450.pdf

我真没看过

**Comment by vycezhong** [comment]
batch normalization是对batch那一维度做normalize

layer normalization是对hidden size那一维度做normalize 

bn有缺点，mini-batch特别小的时候，显然mean和var都比较bias，不太适用

**Comment by yzh119** [comment]
建议直接看group norm嗷
