### ISSUE TITLE
arXiv '20 | Transformers are RNNs: Fast Autoregressive Transformers with Linear Attention

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#76]
https://arxiv.org/pdf/2006.16236.pdf

from: https://www.reddit.com/r/MachineLearning/comments/higqq0/r_transformers_are_rnns_fast_autoregressive/

**Comment by yzh119** [comment]
感觉实验太弱了。。

**Comment by vycezhong** [comment]
motivation是因为transformer的 self-atttention需要O(N^2)的时间复杂度和空间复杂度，N是序列长度. 对于长序列时间和空间开销太大，想降低到O(N).

标准的self-attention可以写成
![image](https://user-images.githubusercontent.com/25879526/87626501-0bae1500-c75f-11ea-99c1-153fe40cc812.png)
其中
![image](https://user-images.githubusercontent.com/25879526/87626509-12d52300-c75f-11ea-911c-cb6302e11d40.png)

作者想用一个kernel替代SIM(). 得到
![image](https://user-images.githubusercontent.com/25879526/87626567-4152fe00-c75f-11ea-9ec9-8c971c8a602b.png)

而Q可以提出来

![image](https://user-images.githubusercontent.com/25879526/87626595-4e6fed00-c75f-11ea-94dc-4f408653894e.png)

这样可以事先计算好
![image](https://user-images.githubusercontent.com/25879526/87626621-621b5380-c75f-11ea-88ec-4df32ceab4d1.png)
后面只需要直接用结果就行

时间复杂度和空间复杂度都降到O(N)

实际中他们用了
![image](https://user-images.githubusercontent.com/25879526/87626661-7b240480-c75f-11ea-8b05-023e1e7682af.png)

decode的时候是autoregressive, 需要mask掉后面的position. 
![image](https://user-images.githubusercontent.com/25879526/87626718-a9a1df80-c75f-11ea-8d7c-2e50f351fac4.png)

同样改写成
![image](https://user-images.githubusercontent.com/25879526/87626736-b58da180-c75f-11ea-9752-1ed27d333fc1.png)

然后引入S_i, Z_i

![image](https://user-images.githubusercontent.com/25879526/87626751-be7e7300-c75f-11ea-9b4d-fc50dd111e5e.png)

可以简化为
![image](https://user-images.githubusercontent.com/25879526/87626763-c5a58100-c75f-11ea-9960-42343cfe543c.png)

所以到这里可以把Transformer看作是一个RNN, 对序列长度N做循环

![image](https://user-images.githubusercontent.com/25879526/87626868-fab1d380-c75f-11ea-89a4-23ae8e36d978.png)

![image](https://user-images.githubusercontent.com/25879526/87626890-069d9580-c760-11ea-8c2d-91b1ece0b9ac.png)

实验跟标准transformer和reformer #18 对比

第一个实验居然是假数据实验。。。第二个是图像生成，第三个是语音识别。这些任务有些奇怪，我不知道为什么不做做翻译？
___

他们居然还注册了linear-transformer的域名。。。。

https://linear-transformers.com/
