### ISSUE TITLE
arXiv '20 | End-to-End Object Detection with Transformers

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#79]
https://arxiv.org/pdf/2005.12872.pdf

忘记标了

**Comment by yzh119** [comment]
This paper is neat

**Comment by vycezhong** [comment]
不是很熟object detection,只能粗浅看下。

首先文章的出发点是想消除obect detection中的一些非dl操作，比如non-max suppression和anchor generation. 搞一个end2end的模型, 输出就直接是一组(class, bbox). 这样怎么算loss呢？ 作者搞了一个二分匹配算法来确定哪个输出对应哪个ground truth，用一个叫做匈牙利loss作为损失函数. 

然后是模型
![image](https://user-images.githubusercontent.com/25879526/87409951-45184080-c5f8-11ea-821a-125a5c309445.png)
照例是CNN提取特征，flatten，加入positional encoding，输入到transformer encoder; decoder的输入是N个learnt positional encoding, 又叫做object queries ，和encoder的输入做attention, decoder的N个输出分别送到FFN得到结果. 

作者说用transformer能够知道所有object的全局信息，有点玄学嗷。
