### ISSUE TITLE
arXiv '20 | Accelerated Large Batch Optimization of BERT Pretraining in 54 minutes

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#80]
https://arxiv.org/pdf/2006.13484.pdf

组里mentors力作

192台p3.24xlarge？？？害怕

这是要榨干AWS吗

**Comment by ZheyuYe** [comment]
👍

**Comment by yzh119** [comment]
你算一下机时我觉得还好

**Comment by vycezhong** [comment]
本文是在LAMB #3 上的改进，提出了LANS
![image](https://user-images.githubusercontent.com/25879526/87219487-2c0c5700-c38e-11ea-9ea6-048eed642515.png)

第一个改进是加了一个对g_t的normalize，除以L2 norm. 这个比较trivial. 

第二个改进是将nesterov momentum融入进了LAMB. 先把原来的更新那步拆成这样

![image](https://user-images.githubusercontent.com/25879526/87219498-4f370680-c38e-11ea-9170-26d4eda2bc09.png)

然后效仿nesterov momentum,把$m_{t-1}$改成了$m_t$，然后去掉了$1/(1-\beta^t_1$，得到了

![image](https://user-images.githubusercontent.com/25879526/87219526-8b6a6700-c38e-11ea-9901-69ebbb0050a5.png)

有趣的是，这恰好是带一阶mom和不带一阶mom的线性组合. 

文章另一个贡献是提出了加入一段constant lr. 一般的lr策略是先warmup然后下降. 由于lr不能无限增大，所以就考虑加一段维持最大lr. 

![image](https://user-images.githubusercontent.com/25879526/87219545-c10f5000-c38e-11ea-9946-50c188def3c6.png)

结果
![image](https://user-images.githubusercontent.com/25879526/87219682-f49eaa00-c38f-11ea-8416-02c46ec5c652.png)

另外mxnet已经加上lans了
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/optimizer/lans.py
___

应该还是在进行中的工作，还差一些实验和理论分析，搞完后应该能中不错的会议.
