### ISSUE TITLE
CVPR '20 | Momentum Contrast for Unsupervised Visual Representation Learning

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#82]
https://arxiv.org/pdf/1911.05722.pdf

**Comment by vycezhong** [comment]
看了好几天，对cv不了解读起来好艰难。。。

background是做对比学习，通过构造正样本（数据增强），采样负样本，计算contrastive loss来训练，loss一般长这样：

![image](https://user-images.githubusercontent.com/25879526/88271991-9b793380-cd0a-11ea-88fb-5c3a0b9c49dc.png)

q是当前input的feature（query），k+是正样本的feature，其他k是负样本（keys）


做这种contrastive loss mechanism差不多有三种方法

![image](https://user-images.githubusercontent.com/25879526/88271835-60770000-cd0a-11ea-84b3-93a2d28ca015.png)

这三个方法区别在于 1）如何采样负样本（文中叫keys），2）encoder如何更新

正常人的想法一般都是a）那种吧，encoer感觉应该得是一样的，keys的多少取决于batch size。当batch size太大的时候容易显存不够（_没看懂，怎么感觉更费显存？？？_）。

第二种是memory bank那样 #86 , 每次从一个memory bank中采样。这个问题在于memory bank的keys是由之前的encoder更新的，然后q又是被当前的encoder计算的，这两者可能不一致。

然后作者搞了一个momentum encoder来作为keys的encoder
![image](https://user-images.githubusercontent.com/25879526/88273049-31618e00-cd0c-11ea-95bc-60480743c914.png)

实际中m=0.999，所以这是一个非常慢的更新，keys的encoder参数基本不变

具体过程还是看代码比较清晰
![image](https://user-images.githubusercontent.com/25879526/88273266-7c7ba100-cd0c-11ea-8b0c-46252b8670b4.png)

最后还有一个shuffle BN的trick，没怎么看懂。


实验
![image](https://user-images.githubusercontent.com/25879526/88273688-28bd8780-cd0d-11ea-869b-a9bb50b1b756.png)

end2end在accu上挺接近，但是由于K=batch size，而batch size不能过大，导致到1024之后就挂了。之前的memory bank要输好几个点

与其他方法比较
![image](https://user-images.githubusercontent.com/25879526/88273852-67ebd880-cd0d-11ea-8a46-2fd154879134.png)

后面还有一堆检测的实验懒得看了

____

感觉idea很奇怪，可能是我太菜了

为什么end2end那么耗显存而moco却不那么耗也没看懂。。

**Comment by ganler** [comment]
因为moco把instance discrimination拖到了时间维度，并且用动量encoder代替了e2e的梯度训练出来的encoder。
