### ISSUE TITLE
ACL '20 | HAT: Hardware-Aware Transformers for Efficient Natural Language Processing

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#89]
https://arxiv.org/pdf/2005.14187.pdf

**Comment by vycezhong** [comment]
主要idea是想搜索一个更小的transformer满足不同硬件的latency限制。文章的亮点是直接用latency作为衡量metric，而不是常用的FLOPS。因为作者观察到FLOPS不能准确反映latency，如下图

![image](https://user-images.githubusercontent.com/25879526/87952869-e7df2c00-cadc-11ea-96bc-ef7b89c04bf4.png)

上图显示：1）相同的FLOPS却可能有不同的latency 2）不同结构transformer在不同硬件上有很大差异，比如embedding layer增大对于在Raspberry Pi有很大影响，而对于GPU几乎没影响。

transformer的搜索空间主要来自：1）decoder可以attend倒数1 2 3层的encoder输出；2）不同层的number of heads, hidden dim不一样, embedding dim和layer num也是弹性的

但是这么多模型不可能每个都训练一遍测个BLEU和latency，这里的做法是搞了一个SuperTransformer，可以说是所有可能Transformer的交集，包含了所有的可能。搜索出来的transformer都是SuperTransformer的子集，叫做SubTransformer。 训练的时候 sample一部分SubTransformer做训练。这个操作说实话我有点震惊。。。

然后选择一些SubTransformer真实测量其在不同平台的latency，构建一个(SubTransformer architecture, measured latency）的数据集，训练一个latency predictor. 

![image](https://user-images.githubusercontent.com/25879526/87954611-31307b00-cadf-11ea-91ad-2b9bf9e2390b.png)

输入是layer num, embed dim, average hidden dim, average self-attention heads.... 输出就是latency. 看上去预测器预测的很准.

最后就是做一个search，value就是预测器的输出，很简单...去掉不满足latency条件的.

实验：
![image](https://user-images.githubusercontent.com/25879526/87954841-7ce32480-cadf-11ea-8c09-dd30f8f663e3.png)

实验分析部分很有趣
1. 10%的decoder会attend 3层encoder layer, 40%会attend 2层encoder layer. 这证明了 1)的必要性
2. GPU model wide but shallow, Raspberry Pi model deep but thin. 

____

个人觉得SuperTransformer那里怪怪的，那样做真的行吗，BLUE能看吗？还是我没看懂？

另外我怀疑主要的speedup是来自a smaller model而不是a more efficient architecture...不过不同硬件上搜出来的architecture更有特点很有趣.

**Comment by vycezhong** [comment]
忽略了一点：搜索部分是寻找val loss最低的又满足latency条件的model，找到后会重新训练SubTransformer然后得到最终的BLEU

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by ganler** [comment]
flops不太能代表latency多一些具体原因（关于gpu的
知乎上有篇文章进行了解释，基本上是因为访存占大头

**Comment by vycezhong** [comment]
> flops不太能代表latency多一些具体原因（关于gpu的
> 知乎上有篇文章进行了解释，基本上是因为访存占大头

Yep. I have read that.

**Comment by yzh119** [comment]
Please read this paper: https://arxiv.org/pdf/2007.00072.pdf

**Comment by vycezhong** [comment]
刚看到一个词 weight-sharing NAS，感觉很像
