### ISSUE TITLE
Stanford EE 364A | Convex Optimization

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#91]
https://www.youtube.com/playlist?list=PL3940DD956CDF0622

https://web.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf

from: shuai 

优化还是挺常用的，书太厚了我估计我啃不完qwq，还是直接看视频吧

____

2020 9 1 Update

COMP3230也上这本书，notes直接记这吧…

**Comment by vycezhong** [comment]
## 优化定义

Given a set D (**domain**), and a real-value func f: D -> R (**objective function**)

最小化问题: 找到x \in D, 使得 f(x) <= f(y) for all y \in D 

最大化问题: 找到x \in D, 使得 f(x) >= f(y) for all y \in D 


一个优化问题一般包括：
- 一个目标函数 $f_0: R^n -> R$
- m个限制函数 $f_i: R^n -> R, i =1...m$
- 一个常数向量 $\mathbb{b} = (b_1, ... b_m) $

找到一个最优的x 使得$f_0$最大/最小并且满足所有限制$f_i$. 

这门课限定$f_0$和$f_i$都是凸的. 因为非凸的非常难解. 

## Convex

Convex定义: f(x)是凸的当且仅当
1. domain是凸集 x \in D
2. 满足 f(ax + by) <= af(x) + bf(y) if a + b = 1, a >= 0, b >= 0 (右式其实就是两点线段上的任何一点)

Examples:
1. 线性函数，f(x) = c^T x （显然）
2. 一些二次函数 f(x) = x^2 （开口向上的应该都是）

Special Case: 线性规划，最小二乘

**Comment by vycezhong** [comment]
介绍了不少概念，感觉这节课是线性代数课
- convex set

- convex combination 

- cones: 如果集合C是cone的话，x \in C和\theta >=0, \theta x \in C
    - convex cone
        - proper cone

这门课所有向量都是列向量. 

$S^n$ 是对称nxn矩阵，$S^n_{+}$表示半正定矩阵( $Z^T X Z \geq 0 \forall Z \in R^n$ ), $S^n_{++}$表示正定矩阵( $Z^T X Z \geq \forall Z \in R^n$ )

介绍了generalized inequalities，用于比较向量和矩阵，要求比较严格（需要全部elements > or < ，所以有的既不是> nor <)

**Comment by vycezhong** [comment]
# Convex Function

常见convex函数on R
1. affine: ax+b for any a, b
2. exp(x, a) for any a
3. pow(x, a) on R++, for a>=1 or a <=0
4. |x|^p, p>=1 
5. negative entropy: xlogx on R++

常见convex函数on R^n
1. affine: a^Tx + b
2. norm :for p >= 1 (proof left as exercise)

**sublevel set**: f(x)小于a的的dom范围

sublevel set的凸函数还是凸的，但是如果一个函数所有sublevel sets都是凸的，这个函数不一定是凸的. 

**epigrap**: $epi f={(x,t) \in R^n+1 | x \in dom f, f(x) <= t}$ 这是一个集合\in R^n+1

f是凸的当且仅当epi f是凸集 (proff left as exercise)

**可导函数**

f是可导的，当且仅当dom f是开集，且梯度处处存在.

f是凸的 => f是连续的
但不能推出处处可导.

**一阶条件**: 凸集上的可导函数f是凸的，当且仅当

$f(y) \geq f(x) + \nabla f(x)^T (y-x) \forall x, y, \in dom f$

f的一阶近似永远是低估的. 

**二阶可导** 函数f是二阶可导的，当dom f是凸集，且Hessian matrix (注意是对称的)
$\nabla^2 f(x)_{i,j} = \frac{\partial^2 f(x)}{\partial x_i \partial x_j}$
处处存在.

**二阶条件**: 二阶可导函数f是凸的当且仅当Hessian Matrix半正定. 

如果Hessian Matrix正定，二阶可导函数f是严格凸的.  反过来，只能得到Hessian Matrix半正定. (比如f(x)=x^4) 

e.g.

二次函数
$f(x) = 1/2 x^T P x + q^T x + r (P \in S^n)$
$\nabla f(x) = Px + q \quad \nabla^2 f(x) = P$

LSE:$f(x) = \|Ax -b\|^2_2$

$\nabla f(x) = 2A^T(Ax - b)\quad \nabla^2 f(x) = 2A^TA$

**Comment by yzh119** [comment]
这时候github不支持latex的劣势就显示出来了

**Comment by vycezhong** [comment]
> 这时候github不支持latex的劣势就显示出来了

但我不喜欢用gitlab

**Comment by vycezhong** [comment]
github写latex确实不方便，转移到了overleaf...

**Comment by ganler** [comment]
> github写latex确实不方便，转移到了overleaf...

可以写blog？

**Comment by vycezhong** [comment]
基本过了书前半部分，后面算法看了PPT. 书很棒. 写了点总结. 

https://drive.google.com/file/d/1Dyu1auTYN9BWJKFyt_zADEIjnMTccHRG/view?usp=sharing
