### ISSUE TITLE
arXiv '20 | Bootstrap Your Own Latent: A New Approach to Self-Supervised Learning

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#95]
https://arxiv.org/pdf/2006.07733.pdf

BYOL

from: simclrv2 paper

**Comment by vycezhong** [comment]
这篇有点意思，有另辟蹊径的感觉。之前的工作，包括MoCo #82  SimCLR #83  都需要大量的负样本作为对比。constrastive loss，就是要最小化同一张图片的不同view的features的距离，而最大化不同图片的view的feature的距离。这种辨别式的方法（discrminative），的确make sense。

但作者提问，真的需要负样本吗？比如我只算个MSE(z_1, z_2)，最小化这个loss行不行？显然有问题，因为如果模型全部输出0，loss直接是0了，这就是所谓的collapse。而负样本的存在，可以避免这种情况（因为全输出0的话，与负样本的距离也是0了）。

作者无意中发现，如下图所示，如果固定target network(randomly initialized)，我用一个online network去预测target network的输出(z')，居然可以得到18.8%的top1准确率！这远高于训练前的1.4%的准确率。**这是本文的核心动机：给定一个网络（哪怕是随机的），叫做target，我们可以训练一个新的网络，就预测target网络的输出，其最后结果可能会优于原来的网络，这个网络叫做online。这样一来，可以构建一个新的target网络，继续如此训练下去。**
![image](https://user-images.githubusercontent.com/25879526/89377250-fc9a0180-d723-11ea-8adc-3b601b81ac32.png)

这让我想起了周伯通的“左右互博“，难怪取名bootstrap，左右互搏，越来越强。

target的网络更新选择了滑动平均，这点和MoCo #82 一样。
![image](https://user-images.githubusercontent.com/25879526/89377736-02441700-d725-11ea-9841-eefecec8b3bd.png)

online网络多一个prediction的结构，用于把输出转为预测值，和projection一样，就是一个MLP。最后losss是计算预测值和target网络的“真实值”之间的MSE。
![Screenshot-20200805140953-804x126](https://user-images.githubusercontent.com/25879526/89377919-5949ec00-d725-11ea-8bf0-3479400762fd.png)

整个方法，没有用到负样本，应该可以节约很大的计算量。


后面几个ablation很有意思，前两个ablation都是想说：BYOL更加robust（相对于batch size，data augmentation）

1. batch size: 在实际训练中，他们还是选择了large batch（4096），附带LARS, linear LR scaling…

我一开始觉得他们用large batch，可能是想节约训练时间而已。毕竟没有用到负样本，应该不会存在像SimCLR #83 ，这种依赖负样本来学习的方法，所会遇到的问题 —— batch size必须足够大以提供足够的负样本

没想到后面的abalation打脸了。如下左图所示，减少batch size，BYOL的performance也会下降，虽然下降的幅度相比SimCLR较小。这很奇怪，作者在footnote也表示了：唯一涉及到batch size的地方，只有batch normalization。*（好像没用global BN？不知道会不会有影响）*
![image](https://user-images.githubusercontent.com/25879526/89378487-73d09500-d726-11ea-8ee0-028df82d6272.png)

2.data augmentation，如上右图，去掉color distortion后，SimCLR掉了很多点。记得SimCLR解释过，这是因为random crop很容易根据color histogram来判断是否是同一张图片。而相比之下，BYOL掉的更少，所以相比那些方法，对于data augmentation更加robust。

3. bootstrapping：主要是做了一个实验，表明\tau = 0.99的时候最好
![image](https://user-images.githubusercontent.com/25879526/89380353-ee4ee400-d729-11ea-9306-61293d109562.png)

还有一个和SimCLR的对比，没细看

最终结果，现在一般是3个metrics，我只关心ResNet50的数据

1. linear evaluation

![image](https://user-images.githubusercontent.com/25879526/89381119-3e7a7600-d72b-11ea-847e-f28c342b3cac.png)


2. semi-supervised 

![image](https://user-images.githubusercontent.com/25879526/89381170-5225dc80-d72b-11ea-9d77-f8fc2e914018.png)

3. transfer learning

![image](https://user-images.githubusercontent.com/25879526/89381231-679b0680-d72b-11ea-9cd2-b6d6029cfec2.png)


吊打SimCLR是没问题的。但没打过SimCLRv2，这可以理解。SimCLRv2本身就是通过大模型蒸馏，直接对比有些不公平。我相信BYOL也做大模型蒸馏后，不会输给SimCLRv2。

____

这篇文章5个一作……啊这

这篇文章idea实在太棒了，难怪上个月那么火，估计一堆人已经在改进了，过几个月应该可以看到BYOLv2

**Comment by vycezhong** [comment]
看了一圈知乎大佬的回答，又有一些新的理解

的确，BYOL为什么work，还是一个未解之迷。作者只是观测到了一个奇怪的现象，从而引申出了左右互博的方法，然后发现确实work。但这缺乏理论的解释。

这位dalao从偏理论的角度去解释为什么BYOL work.
如何评价Deepmind自监督新作BYOL？ - 慕容腹黑的回答 - 知乎
https://www.zhihu.com/question/402452508/answer/1294166177

里面提到了我刚漏了的一个abalation 
![image](https://user-images.githubusercontent.com/25879526/89383655-72579a80-d72f-11ea-975f-6b8891fcede2.png)

![image](https://user-images.githubusercontent.com/25879526/89383700-83a0a700-d72f-11ea-99a5-8851cf0a0a11.png)

上式\beta = 0就是相当于是BYOL了，也就是只最大化正样本的相似度。上面ablation表面，考虑了负样本反而掉两个点。。。有趣。

**Comment by DTennant** [comment]
Whitening for Self-Supervised Representation Learning 只用正样本训练还有个这篇文章，，直接做了白化让样本尽可能打散，，感觉更合理一点

**Comment by DTennant** [comment]
另外我之前有个实验是给moco的loss加了个margin，能很大程度上减少少量负样本的时候的掉点，https://arxiv.org/abs/2008.00261。。
如果从contrastive 互信息估计的角度说，感觉moco和simclr说的大量负样本可能只是为了把分布估计的准一点，，可能有些替代手段就可以估计准了，不需要这么大量的负样本。。

**Comment by vycezhong** [comment]
> 如果从contrastive 互信息估计的角度说，感觉moco和simclr说的大量负样本可能只是为了把分布估计的准一点，，可能有些替代手段就可以估计准了，不需要这么大量的负样本。。

看table2结果这个margin loss有点nb. 

另外同时self-supervised -> distill + finetune 似乎也不错. 看上去可能的确不需要simclrv2所说的self-supervised -> finetune -> distill. 

orz..

**Comment by DTennant** [comment]
https://openreview.net/forum?id=u8X280hw1Mt

**Comment by vycezhong** [comment]
> https://openreview.net/forum?id=u8X280hw1Mt  

orz. Good luck.
