### ISSUE TITLE
arXiv '20 | What Makes for Good Views for Contrastive Learning?

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/read-papers#99]
https://arxiv.org/pdf/2005.10243.pdf

from: google ai blog

**Comment by vycezhong** [comment]
paper写的让人读不懂，不如直接看blog https://ai.googleblog.com/2020/08/understanding-view-selection-for.html

主要观点是InfoMin principle: 除任务相关的信息，其他信息要尽可能丢弃. 如下面这张图，最左边的重叠太多了，太容易识别为同一张图片了，而最右边那张图，重叠的几乎没有，几乎不可能识别为同一个物体; 中间的才比较适中。

![image](https://user-images.githubusercontent.com/25879526/91258762-bcb4c000-e79f-11ea-8700-eb344104a072.png)

为了验证这个principle，他们以views的互信息为自变量，来测试对最终val accu的影响

他们用InfoNCE来估计互信息。曲线符合U shape，验证了上述的猜想：适中的MI才是最好的。
![image](https://user-images.githubusercontent.com/25879526/91259109-6c8a2d80-e7a0-11ea-8943-54c587480765.png)

更有意思的是，他们搞了一个方法来自动生成遵循infomin principle的views。具体方法没看懂

![image](https://user-images.githubusercontent.com/25879526/91267321-b6294700-e7a5-11ea-9683-3198137d6465.png)
___

文章没中ECCV 2020..... 我不知道reviews是怎么样的，但我读这篇paper真的感觉很困难....

**Comment by ZheyuYe** [comment]
google blog 写的倒是都蛮不错的

**Comment by vycezhong** [comment]
> google blog 写的倒是都蛮不错的

确实

**Comment by ZDstandup** [comment]
感觉写得好像西方文学的感觉，读不懂，前几段的举例我就有点蒙了
